=== bulsu-miggy/bsit3c-bustos-finalproject/StudentResult/xmlfiles/studentresult.dtd
<!ELEMENT strands (strand+)>
<!ELEMENT strand (title,description,media)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT media (#PCDATA)>


<!ATTLIST media type CDATA #IMPLIED>

=== bulsu-miggy/bsit3c-bustos-finalproject/StudentResult/db/strand.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE strands SYSTEM "studentresult.dtd">
<strands><strand><title>STEM</title><description/><media>stem.png</media></strand><strand><title>ABM</title><description/><media>seo.png</media></strand><strand><title>GAS</title><description/><media>education.png</media></strand></strands>

=== bulsu-miggy/bsit3c-bustos-finalproject/StudentResult/xmlfiles/strand.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE strands SYSTEM "studentresult.dtd">
<strands><strand><title>STEM</title><description>stands for Science, Technology, Engineering, and Mathematics strand. Through the &#13;
            STEM strand, senior high school students are exposed to complex mathematical and &#13;
            science theories and concepts which will serve as a foundation for their college&#13;
            courses.</description><media>stem.png</media></strand><strand><title>ABM</title><description>Activity-based management ABM is a means of analyzing a company profitability &#13;
            by looking at each aspect of its business to determine strengths and weaknesses. &#13;
            ABM is used to help management find out which areas of the business are losing &#13;
            money so that they can be improved or cut altogether.</description><media>seo.png</media></strand><strand><title>GAS</title><description>General Academic Strand (GAS) This strand was designed so that indecisive learners &#13;
            can proceed with any college program. Though, learners under this strand will take/may &#13;
            not take bridging programs (depending on the school) for the subjects not taken during &#13;
            Senior High.A</description><media>education.png</media></strand><strand><title>STEM</title><description>stands for Science, Technology, Engineering, and Mathematics strand. Through the &#13;
            STEM strand, senior high school students are exposed to complex mathematical and &#13;
            science theories and concepts which will serve as a foundation for their college&#13;
            courses.</description><media>stem.png</media></strand><strand><title>ABM</title><description>Activity-based management ABM is a means of analyzing a company profitability &#13;
            by looking at each aspect of its business to determine strengths and weaknesses. &#13;
            ABM is used to help management find out which areas of the business are losing &#13;
            money so that they can be improved or cut altogether.</description><media>seo.png</media></strand><strand><title>GAS</title><description>General Academic Strand (GAS) This strand was designed so that indecisive learners &#13;
            can proceed with any college program. Though, learners under this strand will take/may &#13;
            not take bridging programs (depending on the school) for the subjects not taken during &#13;
            Senior High.A</description><media>education.png</media></strand><strand><title>STEM</title><description>stands for Science, Technology, Engineering, and Mathematics strand. Through the &#13;
            STEM strand, senior high school students are exposed to complex mathematical and &#13;
            science theories and concepts which will serve as a foundation for their college&#13;
            courses.</description><media>stem.png</media></strand><strand><title>ABM</title><description>Activity-based management ABM is a means of analyzing a company profitability &#13;
            by looking at each aspect of its business to determine strengths and weaknesses. &#13;
            ABM is used to help management find out which areas of the business are losing &#13;
            money so that they can be improved or cut altogether.</description><media>seo.png</media></strand><strand><title>GAS</title><description>General Academic Strand (GAS) This strand was designed so that indecisive learners &#13;
            can proceed with any college program. Though, learners under this strand will take/may &#13;
            not take bridging programs (depending on the school) for the subjects not taken during &#13;
            Senior High.A</description><media>education.png</media></strand></strands>
